2020-04-24-news5.md
thongtincovid19/thongtincovid19.github.io pull request #137
Opened 2020-04-25 06:00 UTC by tatung

New daily post

2020-04-25 08:28 UTC, thongtincovid19 requested changes

2020-04-25 08:28 UTC, thongtincovid19 commented on _posts/2020-04-24-news5.md
> +Như một biện pháp cứng rắn hơn do không chịu đáp ứng yêu cầu, ngày 24/4 Phủ Osaka đã công bố tên 6 cửa hàng Pachinko không đáp ứng yêu cầu dừng kinh doanh. Đây là một việc chưa có tiền lệ trên cả nướ
`Như một biện pháp cứng rắn hơn do không chịu đáp ứng yêu cầu`

Khó hiểu quá, ai ko đáp ứng yêu cầu? Xong đoạn này lại lặp lại ngay đằng sau.

2020-04-26 07:37 UTC, khanhhoa25 approved these changes

2020-04-26 07:38 UTC, khanhhoa25 commented on _posts/2020-04-24-news5.md
> +Như một biện pháp cứng rắn hơn do không chịu đáp ứng yêu cầu, ngày 24/4 Phủ Osaka đã công bố tên 6 cửa hàng Pachinko không đáp ứng yêu cầu dừng kinh doanh. Đây là một việc chưa có tiền lệ trên cả nướ
em sửa và merge bài rồi nhé

2020-04-26 07:40 UTC, lilydoan approved these changes

2020-04-27 00:44 UTC, thongtincovid19 approved these changes

2020-04-27 00:44 UTC, merged