Update 2020-04-21-thematic1.md
thongtincovid19/thongtincovid19.github.io pull request #202
Opened 2020-04-25 17:48 UTC by lilydoan

Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.

If your intention is to submit a Pull Request, please describe what your pull request achieves.

Thank you!

2020-04-26 02:59 UTC, thongtincovid19 requested changes

2020-04-26 02:59 UTC, thongtincovid19 commented on _posts/2020-04-21-thematic1.md
> +  Số điện thoại chung của Đại sứ quán: +81-80-3590-9136 và 080-3609-5011
Đoạn này chưa xuống dòng

2020-04-26 02:59 UTC, thongtincovid19 commented on _posts/2020-04-21-thematic1.md
> +       050-5375-5524
Format đoạn này không đúng markdown

2020-04-26 04:46 UTC, khanhhoa25 approved these changes

2020-04-27 00:51 UTC, thongtincovid19 requested changes

2020-04-27 00:51 UTC, thongtincovid19 commented on _posts/2020-04-21-thematic1.md
> +Bước 2 Kết bạn với tài khoản Facbook của tất cả các Tư Vấn Viên , nhắn tin thông báo "Họ tên... Email..."
`Facbook`

2020-04-27 00:51 UTC, thongtincovid19 commented on _posts/2020-04-21-thematic1.md
> +
Xuống dòng đoạn này rộng quá nhìn rất xấu. Dùng `  ` (2 dấu cách cuối dòng) để xuống dòng sẽ đẹp hơn.

2020-04-27 00:51 UTC, thongtincovid19 commented on _posts/2020-04-21-thematic1.md
> +
Markdown chưa ổn

2020-04-27 00:51 UTC, thongtincovid19 commented on _posts/2020-04-21-thematic1.md
> +
Xuống dòng quá rộng, nhìn sẽ rất xấu. Dùng `  `(2 dấu cách cuối dòng) thì tốt hơn.

2020-04-28 16:02 UTC, thongtincovid19 approved these changes

2020-04-28 16:02 UTC, merged